formatting action yml file

diff --git a/.github/workflows/validate-rdf.yml b/.github/workflows/validate-rdf.yml
--- a/.github/workflows/validate-rdf.yml
+++ b/.github/workflows/validate-rdf.yml
@@ -1,37 +1,37 @@
 name: validate-rdf-against-shacl
 
-on: [push]
+on: [ push ]
 jobs:
   run-servlet-validate:
-      runs-on: ubuntu-latest
-      steps:
-        - uses: actions/checkout@v2
-          with:
-            fetch-depth: 0
-        - name: Check changed rdf or shacl files
-          id: diffs
-          run: |
-            # See https://github.community/t/check-pushed-file-changes-with-git-diff-tree-in-github-actions/17220/10
-            export DIFF=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }} validate/{rdf,shacl}/*.ttl)
-            echo "$DIFF"
-            # Escape newlines (replace \n with %0A)
-              echo "::set-output name=diff::$( echo "$DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )"
-        - name: Build Validator
-          if: ${{steps.diffs.outputs.dif}}
-          run: docker-compose up -d app
-        - name: validate rdf against shacl
-          if: ${{steps.diffs.outputs.dif}}
-          run: |
-            sleep 1
-            for rdf_file in validate/rdf/* 
-            do 
-              for shacl_file in validate/shacl/*
-              do
-                RESULT=$(curl -s -F "rdf=@$rdf_file" -F "shaclShape=@$shacl_file" "http://localhost:8080/rdfconv/validate")
-                  if [ "$RESULT" != "VALID" ]; then
-                    echo "Error with $rdf_file and $shacl_file"
-                    echo "$RESULT"
-                    exit 1
-                  fi
-              done
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - name: Check changed rdf or shacl files
+        id: diffs
+        run: |
+          # See https://github.community/t/check-pushed-file-changes-with-git-diff-tree-in-github-actions/17220/10
+          export DIFF=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }} validate/{rdf,shacl}/*.ttl)
+          echo "$DIFF"
+          # Escape newlines (replace \n with %0A)
+            echo "::set-output name=diff::$( echo "$DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )"
+      - name: Build Validator
+        if: ${{steps.diffs.outputs.dif}}
+        run: docker-compose up -d app
+      - name: validate rdf against shacl
+        if: ${{steps.diffs.outputs.dif}}
+        run: |
+          sleep 1
+          for rdf_file in validate/rdf/* 
+          do 
+            for shacl_file in validate/shacl/*
+            do
+              RESULT=$(curl -s -F "rdf=@$rdf_file" -F "shaclShape=@$shacl_file" "http://localhost:8080/rdfconv/validate")
+                if [ "$RESULT" != "VALID" ]; then
+                  echo "Error with $rdf_file and $shacl_file"
+                  echo "$RESULT"
+                  exit 1
+                fi
             done
+          done
